version: "3.9"
name: orion-prod
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - orion
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    networks:
      - orion
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=FALSE
    volumes:
      - chroma_data:/chroma/.chroma/index
    networks:
      - orion
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 10

  django:
    build:
      context: ./services/django
      dockerfile: Dockerfile
    command: ["/bin/bash", "./entrypoint.sh", "prod"]
    env_file:
      - ./.env.prod
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    volumes:
      - django_static:/app/staticfiles
      - django_media:/app/media
    networks:
      - orion

  fastapi:
    build:
      context: ./services/fastapi
      dockerfile: Dockerfile
    command: ["/bin/bash", "./entrypoint.sh", "prod"]
    env_file:
      - ./.env.prod
    depends_on:
      redis:
        condition: service_healthy
      chromadb:
        condition: service_started
    networks:
      - orion

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
    volumes:
      - frontend_build:/out
    depends_on:
      - django
      - fastapi
    networks:
      - orion

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - frontend
      - django
      - fastapi
    ports:
      - "80:80"
    volumes:
      - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
      - django_static:/var/www/static:ro
      - django_media:/var/www/media:ro
    networks:
      - orion

networks:
  orion:
    driver: bridge

volumes:
  mysql_data:
  chroma_data:
  django_static:
  django_media:
  frontend_build:

